# Generated by Django 4.2.7 on 2025-10-25 03:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="2FA activé"),
                ),
                (
                    "primary_method",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP (Google Authenticator)"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("backup", "Codes de sauvegarde"),
                        ],
                        default="totp",
                        max_length=20,
                        verbose_name="Méthode principale",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Secret TOTP"
                    ),
                ),
                (
                    "totp_verified",
                    models.BooleanField(default=False, verbose_name="TOTP vérifié"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "sms_verified",
                    models.BooleanField(default=False, verbose_name="SMS vérifié"),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Codes de sauvegarde"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentification à deux facteurs",
                "verbose_name_plural": "Authentifications à deux facteurs",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Clé de session"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Informations appareil"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expire à")),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session 2FA",
                "verbose_name_plural": "Sessions 2FA",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_verified"],
                        name="two_factor__user_id_52cd39_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="two_factor__expires_e8ce29_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Nom de l'appareil"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablette"),
                            ("desktop", "Ordinateur"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appareil",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Empreinte appareil"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localisation"
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(
                        default=True, verbose_name="Appareil de confiance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil de confiance",
                "verbose_name_plural": "Appareils de confiance",
                "ordering": ["-last_used"],
                "unique_together": {("user", "device_fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="TwoFactorCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("backup", "Code de sauvegarde"),
                        ],
                        max_length=20,
                        verbose_name="Type de code",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("expires_at", models.DateTimeField(verbose_name="Expire à")),
                ("is_used", models.BooleanField(default=False, verbose_name="Utilisé")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Utilisé à"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code 2FA",
                "verbose_name_plural": "Codes 2FA",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code_type", "is_used"],
                        name="two_factor__user_id_c647ea_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="two_factor__expires_b7da98_idx"
                    ),
                ],
            },
        ),
    ]
