# Generated by Django 4.2.7 on 2025-10-25 03:52

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la méthode"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wave", "Wave Côte d'Ivoire"),
                            ("orange_money", "Orange Money"),
                            ("mtn_money", "MTN Money"),
                            ("moov_money", "Moov Money"),
                            ("card", "Carte bancaire"),
                            ("cash", "Espèces"),
                            ("bank_transfer", "Virement bancaire"),
                        ],
                        max_length=20,
                        verbose_name="Type de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Frais en pourcentage",
                    ),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais fixes",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=10,
                        verbose_name="Montant minimum",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000000.00"),
                        max_digits=10,
                        verbose_name="Montant maximum",
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration API"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="Icône"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiement",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID externe"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours de traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réponse API"
                    ),
                ),
                (
                    "api_request",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Requête API"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "payment_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone de paiement"
                    ),
                ),
                (
                    "payment_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de paiement"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payment_system.paymentmethod",
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de paiement",
                "verbose_name_plural": "Transactions de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("wave", "Wave"),
                            ("orange", "Orange Money"),
                            ("mtn", "MTN Money"),
                            ("moov", "Moov Money"),
                        ],
                        max_length=20,
                        verbose_name="Type de webhook",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Données reçues")),
                (
                    "signature",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Signature"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook de paiement",
                "verbose_name_plural": "Webhooks de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WavePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wave_merchant_id",
                    models.CharField(max_length=100, verbose_name="ID Marchand Wave"),
                ),
                (
                    "wave_api_key",
                    models.CharField(max_length=200, verbose_name="Clé API Wave"),
                ),
                (
                    "wave_webhook_secret",
                    models.CharField(
                        max_length=200, verbose_name="Secret Webhook Wave"
                    ),
                ),
                (
                    "wave_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Transaction Wave"
                    ),
                ),
                (
                    "wave_payment_url",
                    models.URLField(blank=True, verbose_name="URL de paiement Wave"),
                ),
                (
                    "wave_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Statut Wave"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Téléphone client"),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Nom du client"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wave_payment",
                        to="payment_system.paymenttransaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Wave",
                "verbose_name_plural": "Paiements Wave",
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant du remboursement",
                    ),
                ),
                (
                    "refund_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais de remboursement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours de traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        max_length=200, verbose_name="Raison du remboursement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "api_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réponse API"
                    ),
                ),
                (
                    "external_refund_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID Remboursement externe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payment_system.paymenttransaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remboursement",
                "verbose_name_plural": "Remboursements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrangeMoneyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orange_merchant_id",
                    models.CharField(max_length=100, verbose_name="ID Marchand Orange"),
                ),
                (
                    "orange_api_key",
                    models.CharField(max_length=200, verbose_name="Clé API Orange"),
                ),
                (
                    "orange_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Transaction Orange"
                    ),
                ),
                (
                    "orange_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Statut Orange"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Téléphone client"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orange_money_payment",
                        to="payment_system.paymenttransaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Orange Money",
                "verbose_name_plural": "Paiements Orange Money",
            },
        ),
        migrations.CreateModel(
            name="MTNMoneyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mtn_merchant_id",
                    models.CharField(max_length=100, verbose_name="ID Marchand MTN"),
                ),
                (
                    "mtn_api_key",
                    models.CharField(max_length=200, verbose_name="Clé API MTN"),
                ),
                (
                    "mtn_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Transaction MTN"
                    ),
                ),
                (
                    "mtn_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Statut MTN"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Téléphone client"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mtn_money_payment",
                        to="payment_system.paymenttransaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement MTN Money",
                "verbose_name_plural": "Paiements MTN Money",
            },
        ),
        migrations.CreateModel(
            name="MoovMoneyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moov_merchant_id",
                    models.CharField(max_length=100, verbose_name="ID Marchand Moov"),
                ),
                (
                    "moov_api_key",
                    models.CharField(max_length=200, verbose_name="Clé API Moov"),
                ),
                (
                    "moov_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Transaction Moov"
                    ),
                ),
                (
                    "moov_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Statut Moov"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Téléphone client"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moov_money_payment",
                        to="payment_system.paymenttransaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Moov Money",
                "verbose_name_plural": "Paiements Moov Money",
            },
        ),
    ]
