# Generated by Django 4.2.7 on 2025-10-25 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_system", "0001_initial"),
    ]

    operations = []
