# Generated by Django 4.2.7 on 2025-10-25 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('payment_system', '0002_auto_20251025_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express')], max_length=20, verbose_name='Type de carte')),
                ('last_four_digits', models.CharField(max_length=4, verbose_name='4 derniers chiffres')),
                ('expiry_month', models.PositiveIntegerField(verbose_name="Mois d'expiration")),
                ('expiry_year', models.PositiveIntegerField(verbose_name="Année d'expiration")),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Nom du titulaire')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Carte bancaire',
                'verbose_name_plural': 'Cartes bancaires',
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('moov', 'Moov Money'), ('orange', 'Orange Money'), ('mtn', 'MTN Money')], max_length=20, verbose_name='Fournisseur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte Mobile Money',
                'verbose_name_plural': 'Comptes Mobile Money',
                'unique_together': {('user', 'provider', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('wrong_item', 'Mauvais article'), ('not_delivered', 'Non livré'), ('cancelled', 'Commande annulée'), ('other', 'Autre')], max_length=20, verbose_name='Raison')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('processed', 'Traité')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
            ],
            options={
                'verbose_name': 'Demande de remboursement',
                'verbose_name_plural': 'Demandes de remboursement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='moovmoneypayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='mtnmoneypayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='orangemoneypayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='paymentrefund',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='PaymentWebhook',
        ),
        migrations.RemoveField(
            model_name='wavepayment',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='fee',
            new_name='fees',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='api_config',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fee_percentage',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fixed_fee',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='api_request',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='api_response',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_email',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_phone',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fees_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais (%)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='payment_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_card', 'Carte Bancaire'), ('wave', 'Wave'), ('cash_on_delivery', 'Paiement à la Livraison')], default='mobile_money', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID Transaction Externe'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=999999.99, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant maximum'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminé le'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_system.paymentmethod', verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Référence de paiement'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID Transaction'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.DeleteModel(
            name='MoovMoneyPayment',
        ),
        migrations.DeleteModel(
            name='MTNMoneyPayment',
        ),
        migrations.DeleteModel(
            name='OrangeMoneyPayment',
        ),
        migrations.DeleteModel(
            name='PaymentRefund',
        ),
        migrations.DeleteModel(
            name='WavePayment',
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='payment_system.paymenttransaction', verbose_name='Transaction'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
