# Generated by Django 4.2.7 on 2025-10-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_features_product_specifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_rtl', models.BooleanField(default=False)),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=20)),
                ('time_format', models.CharField(default='%H:%M', max_length=20)),
                ('currency_symbol', models.CharField(default='FCFA', max_length=5)),
                ('currency_position', models.CharField(choices=[('before', 'Avant'), ('after', 'Après')], default='after', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clé de traduction',
                'verbose_name_plural': 'Clés de traduction',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_currency_in_local', models.BooleanField(default=True)),
                ('show_dates_in_local', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='i18n.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de langue',
                'verbose_name_plural': 'Préférences de langue',
            },
        ),
        migrations.CreateModel(
            name='TranslationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='i18n.translationkey')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_values', to='i18n.language')),
            ],
            options={
                'verbose_name': 'Valeur de traduction',
                'verbose_name_plural': 'Valeurs de traduction',
                'ordering': ['language__name'],
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_translations', to='i18n.language')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.tag')),
            ],
            options={
                'verbose_name': 'Traduction de tag',
                'verbose_name_plural': 'Traductions de tags',
                'ordering': ['language__name'],
                'unique_together': {('tag', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('specifications', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_translations', to='i18n.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'Traduction de produit',
                'verbose_name_plural': 'Traductions de produits',
                'ordering': ['language__name'],
                'unique_together': {('product', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'À propos'), ('contact', 'Contact'), ('privacy', 'Politique de confidentialité'), ('terms', "Conditions d'utilisation"), ('shipping', 'Livraison'), ('returns', 'Retours'), ('faq', 'FAQ')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_translations', to='i18n.language')),
            ],
            options={
                'verbose_name': 'Traduction de page',
                'verbose_name_plural': 'Traductions de pages',
                'ordering': ['language__name'],
                'unique_together': {('page_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_translations', to='i18n.language')),
            ],
            options={
                'verbose_name': 'Traduction de catégorie',
                'verbose_name_plural': 'Traductions de catégories',
                'ordering': ['language__name'],
                'unique_together': {('category', 'language')},
            },
        ),
    ]
