# Generated by Django 4.2.0 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('popup_type', models.CharField(choices=[('welcome', 'Bienvenue'), ('newsletter', 'Newsletter'), ('promotion', 'Promotion'), ('cookie_consent', 'Consentement cookies'), ('age_verification', 'Vérification âge'), ('exit_intent', 'Intention de sortie'), ('social_proof', 'Preuve sociale'), ('custom', 'Personnalisé')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('button_text', models.CharField(default='Fermer', max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('trigger_type', models.CharField(choices=[('immediate', 'Immédiat'), ('delay', 'Avec délai'), ('scroll', 'Au scroll'), ('exit_intent', 'Intention de sortie'), ('time_on_page', 'Temps sur page'), ('page_views', 'Nombre de vues')], default='delay', max_length=20)),
                ('trigger_delay', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('trigger_scroll', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trigger_time', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('trigger_page_views', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('show_to_authenticated', models.BooleanField(default=True)),
                ('show_to_anonymous', models.BooleanField(default=True)),
                ('user_types', models.JSONField(default=list)),
                ('pages', models.JSONField(default=list)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('button_color', models.CharField(default='#007bff', max_length=7)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('show_count', models.IntegerField(default=0)),
                ('conversion_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopupInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(choices=[('shown', 'Affiché'), ('closed', 'Fermé'), ('clicked', 'Cliqué'), ('converted', 'Converti')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='popups.popup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction popup',
                'verbose_name_plural': 'Interactions popup',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('math', 'Calcul mathématique'), ('text', 'Texte à recopier'), ('image', 'Sélection d\'image'), ('slider', 'Slider'), ('checkbox', 'Checkbox simple')], max_length=20)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=100)),
                ('options', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Défi captcha',
                'verbose_name_plural': 'Défis captcha',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptchaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_answer', models.CharField(blank=True, max_length=100)),
                ('is_solved', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popups.captchachallenge')),
            ],
            options={
                'verbose_name': 'Session captcha',
                'verbose_name_plural': 'Sessions captcha',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('consent_type', models.CharField(choices=[('necessary', 'Nécessaires'), ('analytics', 'Analytiques'), ('marketing', 'Marketing'), ('preferences', 'Préférences'), ('social', 'Réseaux sociaux')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cookie_name', models.CharField(blank=True, max_length=100)),
                ('cookie_domain', models.CharField(blank=True, max_length=100)),
                ('cookie_duration', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consentement cookie',
                'verbose_name_plural': 'Consentements cookies',
                'ordering': ['consent_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('necessary_cookies', models.BooleanField(default=True)),
                ('analytics_cookies', models.BooleanField(default=False)),
                ('marketing_cookies', models.BooleanField(default=False)),
                ('preferences_cookies', models.BooleanField(default=False)),
                ('social_cookies', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentement utilisateur',
                'verbose_name_plural': 'Consentements utilisateurs',
                'ordering': ['-consent_date'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('version_type', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('language', models.CharField(default='fr', max_length=5)),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politique de confidentialité',
                'verbose_name_plural': 'Politiques de confidentialité',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('version_type', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiées'), ('archived', 'Archivées')], default='draft', max_length=20)),
                ('language', models.CharField(default='fr', max_length=5)),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conditions d\'utilisation',
                'verbose_name_plural': 'Conditions d\'utilisation',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Vérification d'âge", max_length=200)),
                ('message', models.TextField(default="Vous devez avoir au moins 18 ans pour accéder à ce site.")),
                ('min_age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(25)])),
                ('is_active', models.BooleanField(default=False)),
                ('show_on_all_pages', models.BooleanField(default=True)),
                ('pages', models.JSONField(default=list)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('button_color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vérification d\'âge',
                'verbose_name_plural': 'Vérifications d\'âge',
            },
        ),
        migrations.CreateModel(
            name='AgeVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Session vérification d\'âge',
                'verbose_name_plural': 'Sessions vérification d\'âge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together={('user', 'session_key')},
        ),
    ]
