# Generated by Django 4.2.7 on 2025-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popups", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgeVerification",
        ),
        migrations.DeleteModel(
            name="AgeVerificationSession",
        ),
        migrations.AlterField(
            model_name="popup",
            name="popup_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Bienvenue"),
                    ("newsletter", "Newsletter"),
                    ("promotion", "Promotion"),
                    ("cookie_consent", "Consentement cookies"),
                    ("exit_intent", "Intention de sortie"),
                    ("social_proof", "Preuve sociale"),
                    ("custom", "Personnalisé"),
                ],
                max_length=20,
            ),
        ),
    ]
