# Generated by Django 4.2.7 on 2025-10-25 03:52

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "products",
            "0004_alter_category_options_alter_productvariant_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID de propriété"
                    ),
                ),
                (
                    "property_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la propriété"
                    ),
                ),
                ("view_id", models.CharField(max_length=50, verbose_name="ID de vue")),
                ("credentials", models.JSONField(verbose_name="Identifiants")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "track_ecommerce",
                    models.BooleanField(default=True, verbose_name="Suivi e-commerce"),
                ),
                (
                    "track_enhanced_ecommerce",
                    models.BooleanField(
                        default=True, verbose_name="Suivi e-commerce amélioré"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                (
                    "sync_frequency",
                    models.IntegerField(
                        default=24, verbose_name="Fréquence de synchronisation (heures)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Analytics",
                "verbose_name_plural": "Google Analytics",
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du rapport"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=20,
                        verbose_name="Période",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Date de début")),
                ("end_date", models.DateTimeField(verbose_name="Date de fin")),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Total commandes"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Chiffre d'affaires total",
                    ),
                ),
                (
                    "total_products_sold",
                    models.IntegerField(
                        default=0, verbose_name="Total produits vendus"
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valeur moyenne des commandes",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux de conversion (%)",
                    ),
                ),
                (
                    "cart_abandonment_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux d'abandon de panier (%)",
                    ),
                ),
                (
                    "customer_acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Coût d'acquisition client",
                    ),
                ),
                (
                    "customer_lifetime_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valeur vie client",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données détaillées"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Public"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Généré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport de vente",
                "verbose_name_plural": "Rapports de vente",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du template"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "report_type",
                    models.CharField(max_length=50, verbose_name="Type de rapport"),
                ),
                ("query", models.JSONField(verbose_name="Requête")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Paramètres"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Public"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs autorisés",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de rapport",
                "verbose_name_plural": "Templates de rapports",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="Total vues"),
                ),
                (
                    "unique_views",
                    models.IntegerField(default=0, verbose_name="Vues uniques"),
                ),
                (
                    "views_today",
                    models.IntegerField(default=0, verbose_name="Vues aujourd'hui"),
                ),
                (
                    "views_this_week",
                    models.IntegerField(default=0, verbose_name="Vues cette semaine"),
                ),
                (
                    "views_this_month",
                    models.IntegerField(default=0, verbose_name="Vues ce mois"),
                ),
                (
                    "add_to_cart_count",
                    models.IntegerField(default=0, verbose_name="Ajouts au panier"),
                ),
                (
                    "purchase_count",
                    models.IntegerField(default=0, verbose_name="Achats"),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux de conversion (%)",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Chiffre d'affaires",
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Marge bénéficiaire (%)",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Note moyenne",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="Nombre d'avis"),
                ),
                (
                    "wishlist_count",
                    models.IntegerField(default=0, verbose_name="Ajouts aux favoris"),
                ),
                (
                    "comparison_count",
                    models.IntegerField(default=0, verbose_name="Comparaisons"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="products.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics de produit",
                "verbose_name_plural": "Analytics de produits",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du widget"),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "Graphique"),
                            ("metric", "Métrique"),
                            ("table", "Tableau"),
                            ("list", "Liste"),
                            ("gauge", "Jauge"),
                            ("map", "Carte"),
                        ],
                        max_length=20,
                        verbose_name="Type de widget",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "data_source",
                    models.CharField(max_length=100, verbose_name="Source de données"),
                ),
                ("query", models.JSONField(verbose_name="Requête")),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration"
                    ),
                ),
                (
                    "position_x",
                    models.IntegerField(default=0, verbose_name="Position X"),
                ),
                (
                    "position_y",
                    models.IntegerField(default=0, verbose_name="Position Y"),
                ),
                ("width", models.IntegerField(default=4, verbose_name="Largeur")),
                ("height", models.IntegerField(default=3, verbose_name="Hauteur")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Public"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs autorisés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget de tableau de bord",
                "verbose_name_plural": "Widgets de tableau de bord",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="Total sessions"),
                ),
                (
                    "total_page_views",
                    models.IntegerField(default=0, verbose_name="Total pages vues"),
                ),
                (
                    "average_session_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée moyenne de session"
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Total commandes"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total dépensé",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valeur moyenne des commandes",
                    ),
                ),
                (
                    "days_since_first_order",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Jours depuis la première commande",
                    ),
                ),
                (
                    "days_since_last_order",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Jours depuis la dernière commande",
                    ),
                ),
                (
                    "customer_lifetime_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valeur vie client",
                    ),
                ),
                (
                    "customer_segment",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segment client"
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Score de risque",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_analytics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics de client",
                "verbose_name_plural": "Analytics de clients",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, verbose_name="ID de session"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Vue de page"),
                            ("product_view", "Vue de produit"),
                            ("add_to_cart", "Ajout au panier"),
                            ("remove_from_cart", "Suppression du panier"),
                            ("checkout_start", "Début de commande"),
                            ("checkout_complete", "Commande terminée"),
                            ("search", "Recherche"),
                            ("filter", "Filtrage"),
                            ("wishlist_add", "Ajout aux favoris"),
                            ("wishlist_remove", "Suppression des favoris"),
                            ("review_submit", "Soumission d'avis"),
                            ("newsletter_signup", "Inscription newsletter"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("registration", "Inscription"),
                        ],
                        max_length=30,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, verbose_name="URL de la page"),
                ),
                ("referrer", models.URLField(blank=True, verbose_name="Référent")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "product_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Produit"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Catégorie"
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Requête de recherche"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement Analytics",
                "verbose_name_plural": "Événements Analytics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_a_event_t_6c35be_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_a_user_id_ecb128_idx",
                    ),
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="analytics_a_session_533ea7_idx",
                    ),
                ],
            },
        ),
    ]
