# Generated by Django 4.2.7 on 2025-10-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la banque'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de compte'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_description',
            field=models.TextField(verbose_name="Description de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
    ]
