# Generated by Django 4.2.7 on 2025-10-25 03:52

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "products",
            "0004_alter_category_options_alter_productvariant_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du fournisseur"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        max_length=100, verbose_name="Personne de contact"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("address", models.TextField(verbose_name="Adresse")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "country",
                    models.CharField(
                        default="Côte d'Ivoire", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro fiscal"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="30 jours",
                        max_length=100,
                        verbose_name="Conditions de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("suspended", "Suspendu"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("sale", "Vente"),
                            ("return", "Retour"),
                            ("adjustment", "Ajustement"),
                            ("transfer", "Transfert"),
                            ("damage", "Dégât"),
                            ("expired", "Expiré"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité")),
                ("previous_stock", models.IntegerField(verbose_name="Stock précédent")),
                ("new_stock", models.IntegerField(verbose_name="Nouveau stock")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Stock bas"),
                            ("out_of_stock", "Rupture de stock"),
                            ("overstock", "Surstock"),
                            ("expiring", "Expiration proche"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Élevée"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("threshold_value", models.IntegerField(verbose_name="Seuil d'alerte")),
                ("current_stock", models.IntegerField(verbose_name="Stock actuel")),
                ("message", models.TextField(verbose_name="Message d'alerte")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Résolu"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="products.product",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de stock",
                "verbose_name_plural": "Alertes de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrée"),
                            ("out", "Sortie"),
                            ("adjustment", "Ajustement"),
                            ("transfer", "Transfert"),
                            ("return", "Retour"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité")),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Coût unitaire",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Coût total",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction d'inventaire",
                "verbose_name_plural": "Transactions d'inventaire",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("stock_levels", "Niveaux de stock"),
                            ("movements", "Mouvements"),
                            ("alerts", "Alertes"),
                            ("valuation", "Évaluation"),
                            ("turnover", "Rotation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du rapport"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "data",
                    models.JSONField(default=dict, verbose_name="Données du rapport"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport d'inventaire",
                "verbose_name_plural": "Rapports d'inventaire",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SKU fournisseur"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.IntegerField(
                        default=1, verbose_name="Quantité minimum de commande"
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        default=7, verbose_name="Délai de livraison (jours)"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Fournisseur principal"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur de produit",
                "verbose_name_plural": "Fournisseurs de produits",
                "unique_together": {("product", "supplier")},
            },
        ),
    ]
