# Generated by Django 4.2.7 on 2025-10-25 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_product_discount_percentage_product_is_on_sale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Image"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Texte du bouton"
                    ),
                ),
                (
                    "button_url",
                    models.URLField(blank=True, verbose_name="URL du bouton"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bannière",
                "verbose_name_plural": "Bannières",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Section Hero"),
                            ("categories", "Catégories"),
                            ("featured_products", "Produits vedettes"),
                            ("bestsellers", "Meilleures ventes"),
                            ("new_arrivals", "Nouveautés"),
                            ("testimonials", "Témoignages"),
                            ("newsletter", "Newsletter"),
                            ("features", "Fonctionnalités"),
                        ],
                        max_length=50,
                        verbose_name="Type de section",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Contenu")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Section de page d'accueil",
                "verbose_name_plural": "Sections de page d'accueil",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("icon", models.CharField(max_length=50, verbose_name="Icône")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fonctionnalité",
                "verbose_name_plural": "Fonctionnalités",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="Titre"),
                ),
                ("content", models.TextField(verbose_name="Témoignage")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Photo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie mise en avant",
                "verbose_name_plural": "Catégories mises en avant",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
