# Generated by Django 4.2.7 on 2025-10-25 03:52

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la méthode"),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("standard", "Livraison standard"),
                            ("express", "Livraison express"),
                            ("scheduled", "Livraison programmée"),
                            ("pickup", "Retrait en magasin"),
                        ],
                        max_length=20,
                        verbose_name="Type de méthode",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Frais de base"
                    ),
                ),
                (
                    "fee_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais par kg",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Seuil livraison gratuite",
                    ),
                ),
                (
                    "estimated_days_min",
                    models.IntegerField(
                        default=1, verbose_name="Délai minimum (jours)"
                    ),
                ),
                (
                    "estimated_days_max",
                    models.IntegerField(
                        default=3, verbose_name="Délai maximum (jours)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Méthode de livraison",
                "verbose_name_plural": "Méthodes de livraison",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Frais de livraison",
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison estimée"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison réelle"
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False, verbose_name="Livraison programmée"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date programmée"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("preparing", "En préparation"),
                            ("ready", "Prête"),
                            ("in_transit", "En cours de livraison"),
                            ("delivered", "Livrée"),
                            ("failed", "Échec de livraison"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de suivi",
                    ),
                ),
                (
                    "delivery_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom du livreur"
                    ),
                ),
                (
                    "delivery_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone du livreur"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "delivery_notes",
                    models.TextField(blank=True, verbose_name="Notes de livraison"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_orders",
                        to="delivery_system.deliverymethod",
                        verbose_name="Méthode de livraison",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_order",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande de livraison",
                "verbose_name_plural": "Commandes de livraison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la zone"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "postal_codes",
                    models.TextField(
                        help_text="Codes postaux séparés par des virgules",
                        verbose_name="Codes postaux",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Frais de livraison de base en FCFA",
                        max_digits=10,
                        verbose_name="Frais de base",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50000.00"),
                        help_text="Montant minimum pour la livraison gratuite",
                        max_digits=10,
                        verbose_name="Seuil livraison gratuite",
                    ),
                ),
                (
                    "estimated_days_min",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Délai minimum (jours)",
                    ),
                ),
                (
                    "estimated_days_max",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Délai maximum (jours)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zone de livraison",
                "verbose_name_plural": "Zones de livraison",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("preparing", "En préparation"),
                            ("ready", "Prête"),
                            ("in_transit", "En cours de livraison"),
                            ("delivered", "Livrée"),
                            ("failed", "Échec de livraison"),
                            ("cancelled", "Annulée"),
                        ],
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localisation"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="delivery_system.deliveryorder",
                        verbose_name="Commande de livraison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de suivi",
                "verbose_name_plural": "Événements de suivi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_confirm_delivery",
                    models.BooleanField(
                        default=False,
                        verbose_name="Confirmation automatique des livraisons",
                    ),
                ),
                (
                    "notify_on_delivery",
                    models.BooleanField(
                        default=True, verbose_name="Notifier lors de la livraison"
                    ),
                ),
                (
                    "notify_on_delay",
                    models.BooleanField(
                        default=True, verbose_name="Notifier en cas de retard"
                    ),
                ),
                (
                    "allow_scheduled_delivery",
                    models.BooleanField(
                        default=True, verbose_name="Autoriser la livraison programmée"
                    ),
                ),
                (
                    "max_delivery_days",
                    models.IntegerField(
                        default=7, verbose_name="Nombre maximum de jours de livraison"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_delivery_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_settings",
                        to="delivery_system.deliverymethod",
                        verbose_name="Méthode de livraison par défaut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre de livraison",
                "verbose_name_plural": "Paramètres de livraison",
            },
        ),
        migrations.CreateModel(
            name="DeliverySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du créneau"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour de la semaine",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "max_orders",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Nombre maximum de commandes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="delivery_system.deliverymethod",
                        verbose_name="Méthode de livraison",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="delivery_system.deliveryzone",
                        verbose_name="Zone de livraison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau de livraison",
                "verbose_name_plural": "Créneaux de livraison",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {
                    ("zone", "delivery_method", "day_of_week", "start_time")
                },
            },
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="delivery_system.deliveryschedule",
                verbose_name="Créneau programmé",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_orders",
                to="delivery_system.deliveryzone",
                verbose_name="Zone de livraison",
            ),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="delivery_methods",
                to="delivery_system.deliveryzone",
                verbose_name="Zones de livraison",
            ),
        ),
    ]
