# Generated by Django 4.2.7 on 2025-10-26 02:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("delivery_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="Adresse ligne 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Adresse ligne 2",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code postal"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Côte d'Ivoire", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Adresse par défaut"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse de livraison",
                "verbose_name_plural": "Adresses de livraison",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Frais de base"
                    ),
                ),
                (
                    "additional_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais supplémentaires",
                    ),
                ),
                (
                    "total_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Total frais de livraison",
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(verbose_name="Date de livraison estimée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_calculation",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calcul de livraison",
                "verbose_name_plural": "Calculs de livraison",
            },
        ),
        migrations.RemoveField(
            model_name="deliveryorder",
            name="delivery_method",
        ),
        migrations.RemoveField(
            model_name="deliveryorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="deliveryorder",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="deliveryorder",
            name="zone",
        ),
        migrations.AlterUniqueTogether(
            name="deliveryschedule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="deliveryschedule",
            name="delivery_method",
        ),
        migrations.RemoveField(
            model_name="deliveryschedule",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="deliverysettings",
            name="default_delivery_method",
        ),
        migrations.RemoveField(
            model_name="deliverytracking",
            name="delivery_order",
        ),
        migrations.AlterModelOptions(
            name="deliveryzone",
            options={
                "ordering": ["zone_type", "name"],
                "verbose_name": "Zone de livraison",
                "verbose_name_plural": "Zones de livraison",
            },
        ),
        migrations.RemoveField(
            model_name="deliveryzone",
            name="base_fee",
        ),
        migrations.RemoveField(
            model_name="deliveryzone",
            name="city",
        ),
        migrations.RemoveField(
            model_name="deliveryzone",
            name="estimated_days_max",
        ),
        migrations.RemoveField(
            model_name="deliveryzone",
            name="estimated_days_min",
        ),
        migrations.RemoveField(
            model_name="deliveryzone",
            name="free_shipping_threshold",
        ),
        migrations.RemoveField(
            model_name="deliveryzone",
            name="postal_codes",
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2500.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Frais de livraison (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="estimated_days",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Délai de livraison estimé (jours)"
            ),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="zone_type",
            field=models.CharField(
                choices=[
                    ("abidjan", "Abidjan"),
                    ("bassam", "Grand-Bassam"),
                    ("civ_other", "Autres villes de Côte d'Ivoire"),
                    ("international", "International"),
                ],
                default="city",
                max_length=20,
                verbose_name="Type de zone",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Zone active"),
        ),
        migrations.DeleteModel(
            name="DeliveryMethod",
        ),
        migrations.DeleteModel(
            name="DeliveryOrder",
        ),
        migrations.DeleteModel(
            name="DeliverySchedule",
        ),
        migrations.DeleteModel(
            name="DeliverySettings",
        ),
        migrations.DeleteModel(
            name="DeliveryTracking",
        ),
        migrations.AddField(
            model_name="deliverycalculation",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="delivery_system.deliveryzone",
                verbose_name="Zone de livraison",
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery_system.deliveryzone",
                verbose_name="Zone de livraison",
            ),
        ),
    ]
