# Generated by Django 4.2.7 on 2025-10-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Email destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('html_content', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.IntegerField(choices=[(1, 'Très haute'), (2, 'Haute'), (3, 'Normale'), (4, 'Basse'), (5, 'Très basse')], default=3, verbose_name='Priorité')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Tentatives maximum')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programmé pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': "Email en file d'attente",
                'verbose_name_plural': "Emails en file d'attente",
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=20, verbose_name='Téléphone destinataire')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Tentatives maximum')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programmé pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': "SMS en file d'attente",
                'verbose_name_plural': "SMS en file d'attente",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notification In-App')], max_length=20, verbose_name='Type')),
                ('trigger_type', models.CharField(choices=[('order_placed', 'Commande passée'), ('order_confirmed', 'Commande confirmée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('vendor_approved', 'Vendeur approuvé'), ('vendor_rejected', 'Vendeur rejeté'), ('product_review', 'Avis produit'), ('low_stock', 'Stock faible'), ('promotion', 'Promotion'), ('welcome', 'Bienvenue')], max_length=30, verbose_name='Déclencheur')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notification',
                'unique_together': {('type', 'trigger_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='Mises à jour de commande par email')),
                ('email_promotions', models.BooleanField(default=True, verbose_name='Promotions par email')),
                ('email_newsletter', models.BooleanField(default=True, verbose_name='Newsletter par email')),
                ('email_reviews', models.BooleanField(default=True, verbose_name='Avis par email')),
                ('sms_order_updates', models.BooleanField(default=True, verbose_name='Mises à jour de commande par SMS')),
                ('sms_promotions', models.BooleanField(default=False, verbose_name='Promotions par SMS')),
                ('push_order_updates', models.BooleanField(default=True, verbose_name='Mises à jour de commande par push')),
                ('push_promotions', models.BooleanField(default=True, verbose_name='Promotions par push')),
                ('push_reviews', models.BooleanField(default=True, verbose_name='Avis par push')),
                ('in_app_order_updates', models.BooleanField(default=True, verbose_name='Mises à jour de commande in-app')),
                ('in_app_promotions', models.BooleanField(default=True, verbose_name='Promotions in-app')),
                ('in_app_reviews', models.BooleanField(default=True, verbose_name='Avis in-app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notification In-App')], max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échoué'), ('read', 'Lu')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Modèle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
