# Generated by Django 4.2.7 on 2025-10-25 01:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_product_discount_percentage_product_is_on_sale_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["name"],
                "verbose_name": "Variante de produit",
                "verbose_name_plural": "Variantes de produit",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="product",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="created_at",
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Icône FontAwesome"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Marque"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Dimensions (L x l x H)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Poids (kg)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Image principale"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 étoile"),
                    (2, "2 étoiles"),
                    (3, "3 étoiles"),
                    (4, "4 étoiles"),
                    (5, "5 étoiles"),
                ],
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre de l'avis"),
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="ProductViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Clé de session",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vu le"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="products.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de vue",
                "verbose_name_plural": "Historique des vues",
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "product", "session_key")},
            },
        ),
    ]
