# Generated by Django 4.2.7 on 2025-10-25 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_alter_category_options_alter_productvariant_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "verbose_name": "Variante de produit",
                "verbose_name_plural": "Variantes de produit",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="category",
            name="order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="is_main",
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Image principale",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 étoile"),
                    (2, "2 étoiles"),
                    (3, "3 étoiles"),
                    (4, "4 étoiles"),
                    (5, "5 étoiles"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "name")},
        ),
    ]
