# Generated by Django 4.2.7 on 2025-10-26 01:14

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Caractéristiques'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Spécifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Instructions d'utilisation"),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Informations de garantie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
